### ISSUE TITLE
Взять и переписать

### ISSUE THREAD

**Issue by zenwalker** [zenwalker/opencart-exchange1c#40]
Я вот что подумал. Пора бы всё взять и переписать, с текущим говнокодом работать уже не возможно. Естественно, переписать под OpenCart 2.0. Один я этого делать не хочу, поэтому предлагаю собраться, собрать денег на каком-нибудь Бумстартере и сесть за работу вместе.

**Comment by zenwalker** [comment]
Желающие могут написать здесь или намылить мне письмо. Организуем где-нибудь чатик, всё обсудим.

**Comment by hunternsk** [comment]
да вроде немного гавнокода, когда в него погрузишься с головой ))
я переписал всё под 2.0 и битрикса модуль, но у меня там специфичных для заказа костылей такая куча, что я даж это не выкладываю))

**Comment by zenwalker** [comment]
Всё это выглядит не опрятно и, скажем так, не продакшн-реди. Я вообще эту ерунду за вечер на коленке сделал. В общем, можно сделать лучше, в полной мере реализовать поддержку протокола, характеристик, обмена заказами, обеспечить покрытие тестами. Коммерческие перспективы есть, ибо спрос, прямо скажем, не маленький.

**Comment by zenwalker** [comment]
@hunternsk Окей. У тебя ящик в профиле не указан, напиши его или сам мне напиши.

**Comment by hunternsk** [comment]
@zenwalker написал

**Comment by kharkevich** [comment]
@zenwalker @hunternsk  я тоже хочу делать под 2.0
