### ISSUE TITLE
импортируется только 1 товар

### ISSUE THREAD

**Issue by Doncode** [zenwalker/opencart-exchange1c#43]
В 1с 1499 товаров.
Импорт проходит вроде бы успешно, но добавляется только 1 товар.

настройки
Сбрасывать товары:	+
Сбрасывать категории:	+
Сбрасывать производителей:	+
Сбрасывать атрибуты:	+
Сбрасывать количество товаров: +

**Comment by zenwalker** [comment]
VQmod патч применился криво.

**Comment by Doncode** [comment]
как проверить?

**Comment by zenwalker** [comment]
У тебя VQmod вообще стоит? Если да, значит где-то поломалась совместимость. Сноси патч и вручную пиши.

1. `admin/catalog/models/product.php`, в конец метода `addProduct` допиши строку `return $product_id`,
2. `admin/catalog/models/category.php`, в конец метода `addCategory` допиши строку `return $category_id`.
3. `admin/catalog/models/attribute.php`, в конец метода `addAttribute` допиши строку `return $attribute_id`.
3. `admin/catalog/models/manufacturer.php`, в конец метода `addManufacturer` допиши строку `return $manufacturer_id`.

**Comment by Doncode** [comment]
Я решил проблему. позже пришлю патч. 
проблема была из за пустого sku
